# Generated by Django 5.0a1 on 2024-02-09 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0029_user_is_content_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCreator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='creators_profile_photos/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='creators_cover_photos/')),
                ('about_me', models.TextField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('percentage_mark_school', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stream_school', models.CharField(blank=True, max_length=100, null=True)),
                ('bachelor_university_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bachelor_stream', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage_mark_bachelor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('masters_university_name', models.CharField(blank=True, max_length=255, null=True)),
                ('masters_stream', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage_mark_masters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('work_experience', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_awarded', models.DateField()),
                ('content_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='firstApp.contentcreator')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='content_creator_documents/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('content_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='firstApp.contentcreator')),
            ],
        ),
    ]
