# Generated by Django 5.0a1 on 2024-02-12 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0030_contentcreator_award_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentcreator',
            name='bachelor_stream',
        ),
        migrations.RemoveField(
            model_name='contentcreator',
            name='bachelor_university_name',
        ),
        migrations.RemoveField(
            model_name='contentcreator',
            name='masters_stream',
        ),
        migrations.RemoveField(
            model_name='contentcreator',
            name='masters_university_name',
        ),
        migrations.RemoveField(
            model_name='contentcreator',
            name='percentage_mark_bachelor',
        ),
        migrations.RemoveField(
            model_name='contentcreator',
            name='percentage_mark_masters',
        ),
        migrations.RemoveField(
            model_name='contentcreator',
            name='percentage_mark_school',
        ),
        migrations.RemoveField(
            model_name='contentcreator',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='contentcreator',
            name='stream_school',
        ),
        migrations.RemoveField(
            model_name='contentcreator',
            name='work_experience',
        ),
        migrations.RemoveField(
            model_name='contentcreator',
            name='years_of_experience',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('School', 'School'), ('Bachelor', 'Bachelor'), ('Master', 'Master')], max_length=100)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('percentage_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stream', models.CharField(blank=True, max_length=100, null=True)),
                ('content_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='firstApp.contentcreator')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('years_of_experience', models.IntegerField()),
                ('description', models.TextField()),
                ('content_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='firstApp.contentcreator')),
            ],
        ),
    ]
