# Generated by Django 4.2.5 on 2024-02-19 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0031_remove_contentcreator_bachelor_stream_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCreators',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='creators_profile_photos/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='creators_cover_photos/')),
                ('about_me', models.TextField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('years_of_experience', models.IntegerField()),
                ('description', models.TextField()),
                ('content_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='firstApp.contentcreators')),
            ],
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('School', 'School'), ('Bachelor', 'Bachelor'), ('Master', 'Master')], max_length=100)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('percentage_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stream', models.CharField(blank=True, max_length=100, null=True)),
                ('content_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='firstApp.contentcreators')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='content_creator_documents/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('content_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='firstApp.contentcreators')),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_awarded', models.DateField()),
                ('content_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='firstApp.contentcreators')),
            ],
        ),
    ]
