# Generated by Django 4.2.5 on 2024-02-19 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0032_contentcreators_workexperiences_educations_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentcreator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='document',
            name='content_creator',
        ),
        migrations.RemoveField(
            model_name='education',
            name='content_creator',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='content_creator',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='ContentCreator',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
