# Generated by Django 4.2.5 on 2024-02-19 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0033_remove_contentcreator_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.contentcreators'),
        ),
    ]
