# Generated by Django 4.2.5 on 2024-02-19 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0034_course_content_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.collegeuser'),
        ),
    ]
