# Generated by Django 4.2.5 on 2024-02-29 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0036_alter_course_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.contentcreators')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.normaluser')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.normaluser')),
            ],
        ),
    ]
