# Generated by Django 4.2.5 on 2024-03-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0039_alter_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
