# Generated by Django 4.2.5 on 2024-03-04 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0040_message_file_attachment_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymembership',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='firstApp.community'),
        ),
    ]
