# Generated by Django 4.2.5 on 2024-03-05 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0041_alter_communitymembership_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.contentcreators'),
        ),
        migrations.AlterField(
            model_name='post',
            name='college_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.collegeuser'),
        ),
    ]
