# Generated by Django 4.2.5 on 2024-03-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0043_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.courseenrollment'),
        ),
    ]
